# Generated by Django 6.0 on 2025-12-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://unsplash.com/s/photos/restaurant')),
                ('cuisine', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
